management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.endpoint.health.probes.enabled: true

server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/