server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000
---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    hostname: eureka-service