spring:
  application:
    name: loan-evaluation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mortgage-ease
    username: isaimartinez
    password: $Wapoisai123
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/mortgage-ease
    username: postgres
    password: postgres