spring:
  application:
    name: notification-service
  cloud:
    stream:
      bindings:
        processMessage-in-0:
          destination: app-topic
          group: message-consumer-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
  data:
    mongodb:
      uri: mongodb://localhost:27017/loan-app

server:
  port: 8084
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://mongodbuser:mongo@mongodb:27017/loan-app
  cloud:
    stream:
      kafka:
        binder:
          brokers: kakfa:9092