spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/loan-app

server:
  port: 8081

jwt:
  secret: rYbC6ShvZWE6DnZ1/htcxS1VPwN1Ggon5ucF2WjUVc37dPCkPkn63SxlYdg6+Abp7HIoG5ko4vAO7RDO+4VZhw==
  expirationMs: 86400000

logging:
  level:
    com.loanapproval.userservice: TRACE

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://mongodbuser:mongo@mongodb:27017/loan-app