spring:
  application:
    name: application-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/loan-app
  cloud:
    stream:
      bindings:
        appEvents-out-0:
          destination: app-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

feign:
  client:
    config:
      LoanEvaluationFeignClient:
        url: http://localhost:8083
      default:
        loggerLevel: full

loan:
  evaluation:
    url: http://localhost:8083

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://mongodbuser:mongo@mongodb:27017/loan-app
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

feign:
  client:
    config:
      LoanEvaluationFeignClient:
        url: http://loan-evaluation-service:8083

loan:
  evaluation:
    url: http://loan-evaluation-service:8083