server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: application-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/applications/**
        - id: loan-evaluation-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/evaluation/**

jwt:
  secret: rYbC6ShvZWE6DnZ1/htcxS1VPwN1Ggon5ucF2WjUVc37dPCkPkn63SxlYdg6+Abp7HIoG5ko4vAO7RDO+4VZhw==
  expirationMs: 3600000 # 1 hour

logging:
  level:
    root: DEBUG # Temporarily to catch all debug logs
    org.springframework.web.cors: TRACE
    org.springframework.cloud.gateway: DEBUG # Keep this
    com.loanapproval.gatewayservice.filter: DEBUG # Keep this, ensure package is exact
    org.springframework.security: TRACE # Keep this
    io.jsonwebtoken: DEBUG # Add this to see JJWT internal logs if any
