apiVersion: v2
name: application-service-chart
description: A Helm chart for the Application Service microservice
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mortgage-ease-common
    version: 0.1.0
    repository: file://../mortgage-ease-common
