{{- define "mortgage-ease-common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mortgage-ease-common.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mortgage-ease-common.name" . }}
    helm.sh/chart: {{ include "mortgage-ease-common.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mortgage-ease-common.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mortgage-ease-common.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.envFromSecretRefs }}
          envFrom:
          {{- range .Values.envFromSecretRefs }}
          - secretRef:
              name: {{ . | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe_enabled }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe_enabled }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}
          ports:
          {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.configmap.enabled }}
          volumeMounts:
          - name: {{ include "mortgage-ease-common.fullname" . }}
            mountPath: {{ .Values.configmap.mountPath }}
      volumes:
        - name: {{ include "mortgage-ease-common.fullname" . }}
          configMap:
            name: {{ include "mortgage-ease-common.fullname" . }}
      {{- end }}
{{- end -}}
